### ISSUE TITLE
Heart shields/special shields

### ISSUE THREAD

**Issue by nathancastelein** [loopfz/scecret#1]
https://github.com/loopfz/scecret/blob/master/models/card/card.go#L74

In skill test struct, you are making a difference between heart shield and special shield.

AFAIK, heart shield is a kind of special shield, like UT shield. It should not be separated.

**Comment by loopfz** [comment]
UT shield is missing, it's actually an oversight.
"Special" is for the "Shield-Shield", ie scenario-dependant.
I made the distinction explicit in order to generate the matching CardIcons automatically.
Thoughts ?

**Comment by nathancastelein** [comment]
It makes more sense with the UT shield, LGTM now :)

**Comment by loopfz** [comment]
Fixed by https://github.com/loopfz/scecret/commit/497261ccd027f93e01f5d6dafce5d200f4d048a8
